name: "Hello world github actions"
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:
jobs:
  log-ctx:
    runs-on: ubuntu-latest
    steps:
      - name: Log context
        run: |
          echo "GITHUB_WORKFLOW: $GITHUB_WORKFLOW"
          echo "GITHUB_RUN_ID: $GITHUB_RUN_ID"
          echo "BRANCH_NAME: ${{ github.ref }}"
          
  
    